version: "3.3"
networks:
  lnnet:

services:
  nodewatcher:
    container_name: nodewatcher
    image: nodewatcher:latest
    networks:
      - lnnet
    restart: always
    links:
      - postgres
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    container_name: postgres
    networks:
      - lnnet
    image: postgres:14.5-alpine
    restart: always
    environment:
      POSTGRES_DB: depot
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5