version: "3.3"
networks:
  lnnet:

services:
  nodewatcher:
    container_name: nodewatcher
    image: nodewatcher:latest
    networks:
      - lnnet
    restart: always
    links:
      - postgres
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      POSTGRES_HOST: nodewatcher-db
      POSTGRES_PORT: 5432
      POSTGRES_DB: depot
      POSTGRES_USER: nodewatcher
      POSTGRES_PASSWORD: password
      LND_TLS_CERT_PATH: /home/nodewatcher/creds/tls.cert

  postgres:
    container_name: nodewatcher-db
    networks:
      - lnnet
    image: postgres:13.7-alpine
    restart: always
    environment:
      POSTGRES_DB: depot
      POSTGRES_USER: nodewatcher
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5