// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewNode struct {
	ID       int    `json:"id"`
	URL      string `json:"url"`
	Alias    string `json:"alias"`
	Pubkey   string `json:"pubkey"`
	Macaroon string `json:"macaroon"`
	UserID   int    `json:"user_id"`
}

type NewUser struct {
	ID            int    `json:"id"`
	Email         string `json:"email"`
	Password      string `json:"password"`
	PhoneNumber   string `json:"phone_number"`
	SmsEnabled    bool   `json:"sms_enabled"`
	SmsNotifyTime string `json:"sms_notify_time"`
}
